name: saropa_lints_example
description: Example and test fixtures for saropa_lints
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  crypto: ^3.0.0

dev_dependencies:
  custom_lint: ^0.8.0
  saropa_lints:
    path: ../
